config/routes.rb
Rails.application.routes.draw do
  # Routes for customers devise
  devise_for :customers

  as :customer do
    get "signup", to: "devise/registrations#new", as: "signup"
    post "signin" => "devise/sessions#create", as: "signin"
    delete "signout" => "devise/sessions#destroy", as: "signout"
  end

  # Routes for products
  resources :products, only: %i[index show] do
    collection do
      get "filter", "search"
    end
  end

  get "men_products", to: "products#men_products", as: "men_products"
  get "women_products", to: "products#women_products", as: "women_products"

  # Routes for brands
  resources :brands, only: %i[index show]

  # Routes for carts
  resources :carts, only: %i[index]

  # Routes for cart_products
  resources :cart_products, only: %i[create destroy update]

  # Routes for checkout
  resources :checkout, only: %i[index update]

  # Routes for orders
  resources :orders, only: %i[index show create]

  # Routes for order_products
  resources :order_product, only: %i[create]

  # Routes for payment
  scope "/payment" do
    post "create", to: "payment#create", as: "payment_create"
    get "success", to: "payment#success", as: "payment_success"
    get "cancel", to: "payment#cancel", as: "payment_cancel"
  end

  # Homepage
  root to: "products#index"

  # Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Routes for Pages
  get ":permalink", to: "pages#permalink", as: :permalink
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer

  has_many :cart_products, dependent: :destroy
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories

  validates :name, presence: true, uniqueness: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  has_many :orders
  has_one :cart

  validates :full_name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :order_status
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  accepts_nested_attributes_for :products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders

  validates :name, presence: true, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy
  accepts_nested_attributes_for :product_categories, allow_destroy: true

  has_one_attached :image

  has_many :cart_products, dependent: :destroy

  validates :sku, :name, :price, :sale_price, presence: true
  validates :sku, :name, uniqueness: true
  validates :stock, numericality: { only_integer: true }
  validates :price, :sale_price, numericality: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
    @user = current_user
    @province = Province.find(current_user.province_id)
    @sub_total = sub_total
    @total = total
  end

  def update
    new_full_name = params[:full_name].to_s
    new_phone = params[:phone].to_s
    new_address = params[:address].to_s
    new_province = params[:select_province]
    current_user.full_name = new_full_name
    current_user.phone = new_phone
    current_user.address = new_address
    current_user.province_id = new_province
    current_user.save
    redirect_to checkout_index_path
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/checkout/index.html.erb
<div class="row">
  <div class="col-md-8">

    <%= form_with(url: checkout_path(@user), method: "put") do %>
      <p class="lead">
        Email: <%= @user.email %>
      </p>
      <%= text_field_tag(:full_name, @user.full_name, class: "input form-control mb-3") %>
      <%= text_field_tag(:phone, @user.phone, class: "input form-control mb-3") %>
      <%= text_field_tag(:address, @user.address, class: "input form-control mb-3") %>
      <%= select_tag 'select_province', options_from_collection_for_select(Province.all, :id, :name, @user.province_id), class: 'form-control mb-3' %>
      <%= submit_tag("Change Information", class: "btn btn-outline-dark form-control") %>
    <% end %>
  </div>

  <div class="col-md-4">

    <p class="lead">
      Sub Total: <%= @sub_total %>
    </p>

    <% if @province.pst.present? %>
      <p class="lead">
        PST: <%= (@province.pst * @sub_total / 100).round(2) %>
      </p>
    <% else %>
      <p class="lead">
        PST: 0
      </p>
    <% end %>

    <% if @province.gst.present? %>
      <p class="lead">
        GST: <%= (@province.gst * @sub_total / 100).round(2) %>
      </p>
    <% else %>
      <p class="lead">
        GST: 0
      </p>
    <% end %>

    <% if @province.hst.present? %>
      <p class="lead">
        HST: <%= (@province.hst * @sub_total / 100).round(2) %>
      </p>
    <% else %>
      <p class="lead">
        HST: 0
      </p>
    <% end %>

    <p class="lead">
      Total: <%= @total %>
    </p>

    <div>
      <%= button_to "Create Order", orders_path,
        :class => "btn mt-3 btn-outline-dark", :method => :post %>
    </div>

  </div>
</div>