config/routes.rb
Rails.application.routes.draw do
  # Routes for customers devise
  devise_for :customers

  as :customer do
    get "signup", to: "devise/registrations#new", as: "signup"
    post "signin" => "devise/sessions#create", as: "signin"
    delete "signout" => "devise/sessions#destroy", as: "signout"
  end

  # Routes for products
  resources :products, only: %i[index show] do
    collection do
      get "filter", "search"
    end
  end

  get "men_products", to: "products#men_products", as: "men_products"
  get "women_products", to: "products#women_products", as: "women_products"

  # Routes for brands
  resources :brands, only: %i[index show]

  # Routes for carts
  resources :carts, only: %i[index]

  # Routes for cart_products
  resources :cart_products, only: %i[create destroy update]

  # Routes for checkout
  resources :checkout, only: %i[index update]

  # Routes for orders
  resources :orders, only: %i[index show create]

  # Routes for order_products
  resources :order_product, only: %i[create]

  # Routes for payment
  scope "/payment" do
    post "create", to: "payment#create", as: "payment_create"
    get "success", to: "payment#success", as: "payment_success"
    get "cancel", to: "payment#cancel", as: "payment_cancel"
  end

  # Homepage
  root to: "products#index"

  # Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Routes for Pages
  get ":permalink", to: "pages#permalink", as: :permalink
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer

  has_many :cart_products, dependent: :destroy
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories

  validates :name, presence: true, uniqueness: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  has_many :orders
  has_one :cart

  validates :full_name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :order_status
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  accepts_nested_attributes_for :products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders

  validates :name, presence: true, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy
  accepts_nested_attributes_for :product_categories, allow_destroy: true

  has_one_attached :image

  has_many :cart_products, dependent: :destroy

  validates :sku, :name, :price, :sale_price, presence: true
  validates :sku, :name, uniqueness: true
  validates :stock, numericality: { only_integer: true }
  validates :price, :sale_price, numericality: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @products_hash = products_hash
    @sub_total = sub_total
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<div>
  <h2 class="lead">There are <%= products_hash.size() %> products in the cart.</h2>
</div>

<% if flash[:remove_cart] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:remove_cart] %>
  </div>
<% end %>

<% if @products_hash.present? %>
  <% @products_hash.each do |p| %>
    <% product = Product.find(p[0]) %>
    <div class="card m-2">
      <div class="card-body">
        <div class="row">
          <div class="col-md-3">
            <% if product.image.present? %>
              <%= image_tag product.image, class: "card-img" %>
            <% end %>
          </div>

          <div class="col-md-7 offset-2">

            <p class="lead">
              <%= product.name %>
            </p>

            <p>
              Price: <%= product.sale_price %>
            </p>

            <p>
              Quantity: <%= p[1] %>
            </p>

            <div>
              <%= form_with url: cart_product_path(product), method: :put do %>
                <%= hidden_field_tag(:id, product.id) %>
                <div class="row">
                  <div class="col-md-6">
                    <%= number_field(:quantity, :value, in: 1..20, step: 1, class: 'form-control') %>
                  </div>
                  <div class="col-md-6">
                    <%= button_tag "Change the quantity of product", class: "btn btn-outline-dark" %>
                  </div>
                </div>
              <% end %>
            </div>

            <div>
              <%= form_with url: cart_product_path(product), method: :delete do %>
                <%= hidden_field_tag(:id, product.id) %>
                <%= button_tag "Remove from Cart", class: "btn mt-3 btn-outline-dark" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

  <!-- total amount section -->
  <div class="card m-1">
    <div class="card-body">
      <div class="row">
        <div class="col-md-7 offset-5">
          <p class="lead">
            Sub Total: <%= @sub_total %>
          </p>

          <div>
            <%= button_to "Checkout", checkout_index_path,
              :class => "btn mt-3 btn-outline-dark", :method => :get %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>