config/routes.rb
Rails.application.routes.draw do
  # Routes for customers devise
  devise_for :customers

  as :customer do
    get "signup", to: "devise/registrations#new", as: "signup"
    post "signin" => "devise/sessions#create", as: "signin"
    delete "signout" => "devise/sessions#destroy", as: "signout"
  end

  # Routes for products
  resources :products, only: %i[index show] do
    collection do
      get "filter", "search"
    end
  end

  get "men_products", to: "products#men_products", as: "men_products"
  get "women_products", to: "products#women_products", as: "women_products"

  # Routes for brands
  resources :brands, only: %i[index show]

  # Routes for carts
  resources :carts, only: %i[index]

  # Routes for cart_products
  resources :cart_products, only: %i[create destroy update]

  # Routes for checkout
  resources :checkout, only: %i[index update]

  # Routes for orders
  resources :orders, only: %i[index show create]

  # Routes for order_products
  resources :order_product, only: %i[create]

  # Routes for payment
  scope "/payment" do
    post "create", to: "payment#create", as: "payment_create"
    get "success", to: "payment#success", as: "payment_success"
    get "cancel", to: "payment#cancel", as: "payment_cancel"
  end

  # Homepage
  root to: "products#index"

  # Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Routes for Pages
  get ":permalink", to: "pages#permalink", as: :permalink
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer

  has_many :cart_products, dependent: :destroy
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories

  validates :name, presence: true, uniqueness: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  has_many :orders
  has_one :cart

  validates :full_name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :order_status
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  accepts_nested_attributes_for :products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders

  validates :name, presence: true, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy
  accepts_nested_attributes_for :product_categories, allow_destroy: true

  has_one_attached :image

  has_many :cart_products, dependent: :destroy

  validates :sku, :name, :price, :sale_price, presence: true
  validates :sku, :name, uniqueness: true
  validates :stock, numericality: { only_integer: true }
  validates :price, :sale_price, numericality: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page]).per(24)
  end

  def men_products
    @men_products = Product.joins(:categories).where(categories: { name: "Men" }).page(params[:page]).per(24)
  end

  def women_products
    @women_products = Product.joins(:categories).where(categories: { name: "Women" }).page(params[:page]).per(24)
  end

  def show
    @product = Product.find(params[:id])
  end

  def search
    keyword_search = "%#{params[:keywords]}%"
    brand_search = params[:select_brand]
    if brand_search == ""
      @result_products_count = Product.where("name LIKE ?", keyword_search)
      @result_products = Product.where("name LIKE ?", keyword_search).page(params[:page])
    else
      @result_products_count = Product.where("name LIKE ? AND brand_id = ?", keyword_search, brand_search)
      @result_products = Product.where("name LIKE ? AND brand_id = ?", keyword_search, brand_search).page(params[:page])
    end
  end

  def filter
    filter = params[:filter_product]
    if filter == "Sale Products"
      @filter_keyword = "Sale Products"
      @filter_products = Product.where("sale_price < price").page(params[:page]).per(24)
    elsif filter == "New Products"
      @filter_keyword = "New Products"
      @filter_products = Product.where("created_at >= ?", Time.zone.today - 3.days).page(params[:page]).per(24)
    else
      @filter_keyword = "All Products"
      @filter_products = Product.all.page(params[:page]).per(24)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="row">
  <div class="card m-5 p-3" style="width: 16rem;">
    <% if product.image.present? %>
      <%= link_to product do %>
        <%= image_tag product.image, alt: "Perfume image", class: "card-img-top" %>
      <% end %>
    <% end %>

    <div class="card-body ">
      <h5 class="card-title lead"> <%= link_to product.name, product %> </h5>

      <div class="col d-flex justify-content-center">
        <%= form_with url: cart_products_path, method: :post do %>
          <%= hidden_field_tag(:id, product.id, autocomplete:"off", id: "id#{product.id}") %>
          <%= button_tag "Add to Cart", class: "btn btn-outline-dark" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/products/filter.html.erb
<% @title = @filter_keyword %>

<h2 class="display-4 text-center"> <%= @filter_keyword %> </h2>

<div>
  <%= form_with(url: filter_products_path, method: :get, local: true) do %>
    <div class="form-row align-items-center">
      <div class="col-auto">
        <label class="form-check-label">
          Filter Products
        </label>
      </div>
      <div class="col-auto">
        <% if @filter_keyword == "All Products" %>
          <%= select_tag 'filter_product', raw("<option selected='selected'>All Products</option>
            <option>Sale Products</option>
            <option>New Products</option>"), :onchange => "this.form.submit();", class: 'form-control' %>
        <% elsif @filter_keyword == "Sale Products" %>
          <%= select_tag 'filter_product', raw("<option>All Products</option>
            <option selected='selected'>Sale Products</option>
            <option>New Products</option>"), :onchange => "this.form.submit();", class: 'form-control' %>
        <% else %>
          <%= select_tag 'filter_product', raw("<option>All Products</option>
            <option>Sale Products</option>
            <option selected='selected'>New Products</option>"), :onchange => "this.form.submit();", class: 'form-control' %>
        <% end %>

      </div>
    </div>
  <% end %>
</div>

<% if flash[:add_cart] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:add_cart] %>
  </div>
<% end %>

<div class="card-deck">
  <%= render @filter_products %>
</div>

<%= paginate @filter_products %>

app/views/products/index.html.erb
<% @title = "Products" %>

<h2 class="text-center">All Products</h2>

<div>
  <%= form_with(url: filter_products_path, method: :get, local: true) do %>
    <div class="form-row align-items-center">
      <div class="col-auto">
        <label class="form-check-label">
          Filter Products
        </label>
      </div>
      <div class="col-auto">
        <%= select_tag 'filter_product', raw("<option>All Products</option><option>Sale Products</option><option>New Products</option>"),
          :onchange => "this.form.submit();", class: 'form-control' %>
      </div>
    </div>
  <% end %>
</div>

<% if flash[:add_cart] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:add_cart] %>
  </div>
<% end %>

<div class="card-deck">
  <%= render @products %>
</div>

<%= paginate @products %>

app/views/products/men_products.html.erb
<% @title = "Mens Products" %>

<h2 class="display-4 text-center">Men Products</h2>

<% if flash[:add_cart] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:add_cart] %>
  </div>
<% end %>

<div class="card-deck">
  <%= render @men_products  %>
</div>

<%= paginate @men_products %>

app/views/products/search.html.erb
<p> Found <%= pluralize(@result_products_count.count, 'Products') %> </p>

<div class="card-deck">
  <%= render @result_products %>
</div>

<%= paginate @result_products %>

app/views/products/show.html.erb
<% @title = @product.name %>

<div class="row">
  <div class="col-5">
    <% if @product.image.present? %>
      <%= image_tag @product.image, class:"img-fluid" %>
    <% end %>
  </div>

  <div class="col-6 offset-1">
    <p class="lead">
      <%= @product.name %>
    </p>

    <p>
      <%= link_to "By #{@product.brand.name}", @product.brand %>
    </p>

    <p>
      Sku: <%= @product.sku %>
    </p>

    <% if @product.sale_price.present? && @product.sale_price < @product.price %>
      <p>
        Price On Sale: <s><%= @product.price %></s> <%= @product.sale_price %>
      </p>
    <% else %>
      <p>
        Price: <%= @product.price %>
      </p>
    <% end %>

    <p>
      Product Information: <%= simple_format(@product.description) %>
    </p>

  </div>
</div>

app/views/products/women_products.html.erb
<% @title = "Womens Products" %>

<h2 class="display-4 text-center">Women Products</h2>

<% if flash[:add_cart] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:add_cart] %>
  </div>
<% end %>

<div class="card-deck">
  <%= render @women_products  %>
</div>

<%= paginate @women_products %>