config/routes.rb
Rails.application.routes.draw do
  # Routes for customers devise
  devise_for :customers

  as :customer do
    get "signup", to: "devise/registrations#new", as: "signup"
    post "signin" => "devise/sessions#create", as: "signin"
    delete "signout" => "devise/sessions#destroy", as: "signout"
  end

  # Routes for products
  resources :products, only: %i[index show] do
    collection do
      get "filter", "search"
    end
  end

  get "men_products", to: "products#men_products", as: "men_products"
  get "women_products", to: "products#women_products", as: "women_products"

  # Routes for brands
  resources :brands, only: %i[index show]

  # Routes for carts
  resources :carts, only: %i[index]

  # Routes for cart_products
  resources :cart_products, only: %i[create destroy update]

  # Routes for checkout
  resources :checkout, only: %i[index update]

  # Routes for orders
  resources :orders, only: %i[index show create]

  # Routes for order_products
  resources :order_product, only: %i[create]

  # Routes for payment
  scope "/payment" do
    post "create", to: "payment#create", as: "payment_create"
    get "success", to: "payment#success", as: "payment_success"
    get "cancel", to: "payment#cancel", as: "payment_cancel"
  end

  # Homepage
  root to: "products#index"

  # Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Routes for Pages
  get ":permalink", to: "pages#permalink", as: :permalink
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer

  has_many :cart_products, dependent: :destroy
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories

  validates :name, presence: true, uniqueness: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  has_many :orders
  has_one :cart

  validates :full_name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :order_status
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  accepts_nested_attributes_for :products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders

  validates :name, presence: true, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy
  accepts_nested_attributes_for :product_categories, allow_destroy: true

  has_one_attached :image

  has_many :cart_products, dependent: :destroy

  validates :sku, :name, :price, :sale_price, presence: true
  validates :sku, :name, uniqueness: true
  validates :stock, numericality: { only_integer: true }
  validates :price, :sale_price, numericality: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% if @title != nil %>
      <title><%= @title %></title>
    <% else %>
      <title>Ecommer</title>
    <% end %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '_variables', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'nav', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'products', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <!-- nav section -->
    <nav class="navbar navbar-expand-sm">
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <p class="nav-link lead"><%= link_to "Homepage", root_path %></p>
          </li>
          <li class="nav-item">
            <p class="nav-link lead"><%= link_to "About Us", permalink_path("about") %></p>
          </li>
          <li class="nav-item">
            <p class="nav-link lead"><%= link_to "Contact Us", permalink_path("contact") %></p>
          </li>
          <li class="nav-item">
            <p class="nav-link lead"><%= link_to "Mens", men_products_url %></p>
          </li>
          <li class="nav-item">
            <p class="nav-link lead"><%= link_to "Womens", women_products_url %></p>
          </li>
        </ul>

        <ul class="navbar-nav">
          <% if customer_signed_in? %>
            <li class="nav-item">
              <p class="nav-link lead"><%= link_to current_customer.email, orders_path %></p>
            </li>
            <li class="nav-item">
              <p class="nav-link lead"><%= link_to "Cart", carts_path %>
              <span class="badge badge-secondary"><%= products_hash.size() %></span></p>
            </li>
            <li class="nav-item">
              <p class="nav-link lead"><%= link_to "Sign Out", destroy_customer_session_path, :method => :delete %></p>
            </li>
          <% else %>
            <li class="nav-item">
              <p class="nav-link lead"><%= link_to "Cart", carts_path %></p>
            </li>
            <li class="nav-item">
              <p class="nav-link lead"><%= link_to "Sign Up", new_customer_registration_path %></p>
            </li>
            <li class="nav-item">
              <p class="nav-link lead"><%= link_to "Sign In", customer_session_path, :method => :post %></p>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div>
      <%= form_with(url: search_products_path, method: :get, local: true) do %>
        <div class=form-group>
          <div class="row">
            <div class="col-6">
              <%= text_field_tag(:keywords, nil, class: "input form-control", placeholder: "Search Products") %>
            </div>
            <div class="col-4">
              <%= select_tag 'select_brand', options_from_collection_for_select(Brand.all, :id, :name), prompt: "All Brand", class: 'form-control' %>
            </div>
            <div class="col-2">
              <%= submit_tag("Search", class: "btn btn-outline-dark form-control") %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/pages/permalink.html.erb
<p class="lead">
  <% if @page != nil %>
    <%= simple_format(@page.content) %>
  <% else %>
    <%= controller.redirect_to root_path %>
  <% end %>
</p>